name: flutter_package_plus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  image_picker: ^1.1.2
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  # geolocator: ^12.0.0 # the package work fine but when i am build app show error any one help in future
  go_router: ^14.1.4
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/apon.jpg
  #   - images/a_dot_ham.jpeg

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: assets/apon.jpg
  color: "#4e94e0"
  ios_content_mode: scaleAspectFill
  android_gravity: center

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700